
namespace TwistedLogik.Ultraviolet.BASS.Native
{
    internal enum BASSConfig : uint
    {
        CONFIG_BUFFER			= 0,
        CONFIG_UPDATEPERIOD	    = 1,
        CONFIG_GVOL_SAMPLE		= 4,
        CONFIG_GVOL_STREAM		= 5,
        CONFIG_GVOL_MUSIC		= 6,
        CONFIG_CURVE_VOL		= 7,
        CONFIG_CURVE_PAN		= 8,
        CONFIG_FLOATDSP		    = 9,
        CONFIG_3DALGORITHM		= 10,
        CONFIG_NET_TIMEOUT		= 11,
        CONFIG_NET_BUFFER		= 12,
        CONFIG_PAUSE_NOPLAY	    = 13,
        CONFIG_NET_PREBUF		= 15,
        CONFIG_NET_PASSIVE		= 18,
        CONFIG_REC_BUFFER		= 19,
        CONFIG_NET_PLAYLIST	    = 21,
        CONFIG_MUSIC_VIRTUAL	= 22,
        CONFIG_VERIFY			= 23,
        CONFIG_UPDATETHREADS	= 24,
        CONFIG_DEV_BUFFER		= 27,
        CONFIG_VISTA_TRUEPOS	= 30,
        CONFIG_IOS_MIXAUDIO	    = 34,
        CONFIG_DEV_DEFAULT		= 36,
        CONFIG_NET_READTIMEOUT	= 37,
        CONFIG_VISTA_SPEAKERS	= 38,
        CONFIG_IOS_SPEAKER		= 39,
        CONFIG_HANDLES			= 41,
        CONFIG_UNICODE			= 42,
        CONFIG_SRC				= 43,
        CONFIG_SRC_SAMPLE		= 44,
        CONFIG_ASYNCFILE_BUFFER = 45,
        CONFIG_OGG_PRESCAN		= 47,
        CONFIG_NET_AGENT		= 16,
        CONFIG_NET_PROXY		= 17,
        CONFIG_IOS_NOTIFY		= 46,
    }
}
