echo off
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\Newtonsoft.Json.dll" Newtonsoft.Json.dll /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Gluon.dll" TwistedLogik.Gluon.dll /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Nucleus.dll" TwistedLogik.Nucleus.dll /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Nucleus.xml" TwistedLogik.Nucleus.xml /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Ultraviolet.dll" TwistedLogik.Ultraviolet.dll /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Ultraviolet.xml" TwistedLogik.Ultraviolet.xml /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Ultraviolet.OpenGL.dll" TwistedLogik.Ultraviolet.OpenGL.dll /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Ultraviolet.OpenGL.xml" TwistedLogik.Ultraviolet.OpenGL.xml /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Ultraviolet.SDL2.dll" TwistedLogik.Ultraviolet.SDL2.dll /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Ultraviolet.SDL2.dll.config" TwistedLogik.Ultraviolet.SDL2.dll.config /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Ultraviolet.BASS.dll" TwistedLogik.Ultraviolet.BASS.dll /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Ultraviolet.BASS.dll.config" TwistedLogik.Ultraviolet.BASS.dll.config /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Ultraviolet.Desktop.dll" TwistedLogik.Ultraviolet.Desktop.dll /Y
echo f | xcopy "..\..\Binaries\AnyCPU\Debug\TwistedLogik.Ultraviolet.UI.Presentation.dll" TwistedLogik.Ultraviolet.UI.Presentation.dll /Y

echo f | xcopy "..\..\Binaries\AnyCPU\Debug\Newtonsoft.Json.dll" Android\Newtonsoft.Json.dll /Y
echo f | xcopy "..\..\Binaries\Android\Debug\TwistedLogik.Gluon.dll" Android\TwistedLogik.Gluon.dll /Y
echo f | xcopy "..\..\Binaries\Android\Debug\TwistedLogik.Nucleus.dll" Android\TwistedLogik.Nucleus.dll /Y
echo f | xcopy "..\..\Binaries\Android\Debug\TwistedLogik.Nucleus.xml" Android\TwistedLogik.Nucleus.xml /Y
echo f | xcopy "..\..\Binaries\Android\Debug\TwistedLogik.Ultraviolet.dll" Android\TwistedLogik.Ultraviolet.dll /Y
echo f | xcopy "..\..\Binaries\Android\Debug\TwistedLogik.Ultraviolet.xml" Android\TwistedLogik.Ultraviolet.xml /Y
echo f | xcopy "..\..\Binaries\Android\Debug\TwistedLogik.Ultraviolet.OpenGL.dll" Android\TwistedLogik.Ultraviolet.OpenGL.dll /Y
echo f | xcopy "..\..\Binaries\Android\Debug\TwistedLogik.Ultraviolet.OpenGL.xml" Android\TwistedLogik.Ultraviolet.OpenGL.xml /Y
echo f | xcopy "..\..\Binaries\Android\Debug\TwistedLogik.Ultraviolet.SDL2.dll" Android\TwistedLogik.Ultraviolet.SDL2.dll /Y
echo f | xcopy "..\..\Binaries\Android\Debug\TwistedLogik.Ultraviolet.BASS.dll" Android\TwistedLogik.Ultraviolet.BASS.dll /Y
echo f | xcopy "..\..\Binaries\Android\Debug\TwistedLogik.Ultraviolet.Android.dll" Android\TwistedLogik.Ultraviolet.Android.dll /Y
echo f | xcopy "..\..\Binaries\Android\Debug\TwistedLogik.Ultraviolet.UI.Presentation.dll" Android\TwistedLogik.Ultraviolet.UI.Presentation.dll /Y
echo f | xcopy "..\..\Binaries\Android\Debug\org.libsdl.app.dll" Android\org.libsdl.app.dll /Y