using Microsoft.VisualStudio.Text;
using Ultraviolet.Presentation.Uvss.Syntax;

namespace Ultraviolet.VisualStudio.Uvss.Parsing
{
    /// <summary>
    /// Represents the result of parsing a UVSS document.
    /// </summary>
    public struct UvssTextParserResult
	{
		/// <summary>
		/// Initializes a new instance of the <see cref="UvssTextParserResult"/> structure.
		/// </summary>
		/// <param name="snapshot">The snapshot from which the document was generated.</param>
		/// <param name="document">The document that was generated by the parser.</param>
		public UvssTextParserResult(ITextSnapshot snapshot, UvssDocumentSyntax document)
		{
			this.Snapshot = snapshot;
			this.Document = document;
		}

		/// <summary>
		/// Gets the snapshot from which the document was generated.
		/// </summary>
		public ITextSnapshot Snapshot { get; }

		/// <summary>
		/// Gets the document that was generated by the parser.
		/// </summary>
		public UvssDocumentSyntax Document { get; }
	}
}
