using System;

#pragma warning disable 1591

namespace TwistedLogik.Ultraviolet.SDL2.Native
{
    public static class SDL_Hint
    {
        public const String FRAMEBUFFER_ACCELERATION = "SDL_FRAMEBUFFER_ACCELERATION";
        public const String RENDER_DRIVER = "SDL_RENDER_DRIVER";
        public const String RENDER_OPENGL_SHADERS = "SDL_RENDER_OPENGL_SHADERS";
        public const String RENDER_DIRECT3D_THREADSAFE = "SDL_RENDER_DIRECT3D_THREADSAFE";
        public const String RENDER_DIRECT3D11_DEBUG = "SDL_HINT_RENDER_DIRECT3D11_DEBUG";
        public const String RENDER_SCALE_QUALITY = "SDL_RENDER_SCALE_QUALITY";
        public const String RENDER_VSYNC = "SDL_RENDER_VSYNC";
        public const String VIDEO_ALLOW_SCREENSAVER = "SDL_VIDEO_ALLOW_SCREENSAVER";
        public const String VIDEO_X11_XVIDMODE = "SDL_VIDEO_X11_XVIDMODE";
        public const String VIDEO_X11_XINERAMA = "SDL_VIDEO_X11_XINERAMA";
        public const String VIDEO_X11_XRANDR = "SDL_VIDEO_X11_XRANDR";
        public const String GRAB_KEYBOARD = "SDL_GRAB_KEYBOARD";
        public const String MOUSE_RELATIVE_MODE_WARP = "SDL_MOUSE_RELATIVE_MODE_WARP";
        public const String VIDEO_MINIMIZE_ON_FOCUS_LOSS = "SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS";
        public const String IDLE_TIMER_DISABLED = "SDL_IOS_IDLE_TIMER_DISABLED";
        public const String ORIENTATIONS = "SDL_IOS_ORIENTATIONS";
        public const String ACCELEROMETER_AS_JOYSTICK = "SDL_ACCELEROMETER_AS_JOYSTICK";
        public const String XINPUT_ENABLED = "SDL_XINPUT_ENABLED";
        public const String GAMECONTROLLERCONFIG = "SDL_GAMECONTROLLERCONFIG";
        public const String JOYSTICK_ALLOW_BACKGROUND_EVENTS = "SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS";
        public const String ALLOW_TOPMOST = "SDL_ALLOW_TOPMOST";
        public const String TIMER_RESOLUTION = "SDL_TIMER_RESOLUTION";
        public const String VIDEO_HIGHDPI_DISABLED = "SDL_VIDEO_HIGHDPI_DISABLED";
        public const String MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK = "SDL_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK";
        public const String VIDEO_WIN_D3DCOMPILER = "SDL_VIDEO_WIN_D3DCOMPILER";
        public const String VIDEO_WINDOW_SHARE_PIXEL_FORMAT = "SDL_VIDEO_WINDOW_SHARE_PIXEL_FORMAT";
        public const String WINRT_PRIVACY_POLICY_URL = "SDL_HINT_WINRT_PRIVACY_POLICY_URL";
        public const String WINRT_PRIVACY_POLICY_LABEL = "SDL_HINT_WINRT_PRIVACY_POLICY_LABEL";
        public const String WINRT_HANDLE_BACK_BUTTON = "SDL_HINT_WINRT_HANDLE_BACK_BUTTON";
        public const String VIDEO_MAC_FULLSCREEN_SPACES = "SDL_VIDEO_MAC_FULLSCREEN_SPACES";
    }
}
