using System;

namespace Ultraviolet.FreeType2.Native
{
#pragma warning disable 1591
    public enum hb_script_t
    {
        HB_SCRIPT_COMMON = ((Byte)'Z' << 24) | ((Byte)'y' << 16) | ((Byte)'y' << 8) | (Byte)'y',
        HB_SCRIPT_INHERITED = ((Byte)'Z' << 24) | ((Byte)'i' << 16) | ((Byte)'n' << 8) | (Byte)'h',
        HB_SCRIPT_UNKNOWN = ((Byte)'Z' << 24) | ((Byte)'z' << 16) | ((Byte)'z' << 8) | (Byte)'z',

        HB_SCRIPT_ARABIC = ((Byte)'A' << 24) | ((Byte)'r' << 16) | ((Byte)'a' << 8) | (Byte)'b',
        HB_SCRIPT_ARMENIAN = ((Byte)'A' << 24) | ((Byte)'r' << 16) | ((Byte)'m' << 8) | (Byte)'n',
        HB_SCRIPT_BENGALI = ((Byte)'B' << 24) | ((Byte)'e' << 16) | ((Byte)'n' << 8) | (Byte)'g',
        HB_SCRIPT_CYRILLIC = ((Byte)'C' << 24) | ((Byte)'y' << 16) | ((Byte)'r' << 8) | (Byte)'l',
        HB_SCRIPT_DEVANAGARI = ((Byte)'D' << 24) | ((Byte)'e' << 16) | ((Byte)'v' << 8) | (Byte)'a',
        HB_SCRIPT_GEORGIAN = ((Byte)'G' << 24) | ((Byte)'e' << 16) | ((Byte)'o' << 8) | (Byte)'r',
        HB_SCRIPT_GREEK = ((Byte)'G' << 24) | ((Byte)'r' << 16) | ((Byte)'e' << 8) | (Byte)'k',
        HB_SCRIPT_GUJARATI = ((Byte)'G' << 24) | ((Byte)'u' << 16) | ((Byte)'j' << 8) | (Byte)'r',
        HB_SCRIPT_GURMUKHI = ((Byte)'G' << 24) | ((Byte)'u' << 16) | ((Byte)'r' << 8) | (Byte)'u',
        HB_SCRIPT_HANGUL = ((Byte)'H' << 24) | ((Byte)'a' << 16) | ((Byte)'n' << 8) | (Byte)'g',
        HB_SCRIPT_HAN = ((Byte)'H' << 24) | ((Byte)'a' << 16) | ((Byte)'n' << 8) | (Byte)'i',
        HB_SCRIPT_HEBREW = ((Byte)'H' << 24) | ((Byte)'e' << 16) | ((Byte)'b' << 8) | (Byte)'r',
        HB_SCRIPT_HIRAGANA = ((Byte)'H' << 24) | ((Byte)'i' << 16) | ((Byte)'r' << 8) | (Byte)'a',
        HB_SCRIPT_KANNADA = ((Byte)'K' << 24) | ((Byte)'n' << 16) | ((Byte)'d' << 8) | (Byte)'a',
        HB_SCRIPT_KATAKANA = ((Byte)'K' << 24) | ((Byte)'a' << 16) | ((Byte)'n' << 8) | (Byte)'a',
        HB_SCRIPT_LAO = ((Byte)'L' << 24) | ((Byte)'a' << 16) | ((Byte)'o' << 8) | (Byte)'o',
        HB_SCRIPT_LATIN = ((Byte)'L' << 24) | ((Byte)'a' << 16) | ((Byte)'t' << 8) | (Byte)'n',
        HB_SCRIPT_MALAYALAM = ((Byte)'M' << 24) | ((Byte)'l' << 16) | ((Byte)'y' << 8) | (Byte)'m',
        HB_SCRIPT_ORIYA = ((Byte)'O' << 24) | ((Byte)'r' << 16) | ((Byte)'y' << 8) | (Byte)'a',
        HB_SCRIPT_TAMIL = ((Byte)'T' << 24) | ((Byte)'a' << 16) | ((Byte)'m' << 8) | (Byte)'l',
        HB_SCRIPT_TELUGU = ((Byte)'T' << 24) | ((Byte)'e' << 16) | ((Byte)'l' << 8) | (Byte)'u',
        HB_SCRIPT_THAI = ((Byte)'T' << 24) | ((Byte)'h' << 16) | ((Byte)'a' << 8) | (Byte)'i',

        HB_SCRIPT_TIBETAN = ((Byte)'T' << 24) | ((Byte)'i' << 16) | ((Byte)'b' << 8) | (Byte)'t',

        HB_SCRIPT_BOPOMOFO = ((Byte)'B' << 24) | ((Byte)'o' << 16) | ((Byte)'p' << 8) | (Byte)'o',
        HB_SCRIPT_BRAILLE = ((Byte)'B' << 24) | ((Byte)'r' << 16) | ((Byte)'a' << 8) | (Byte)'i',
        HB_SCRIPT_CANADIAN_SYLLABICS = ((Byte)'C' << 24) | ((Byte)'a' << 16) | ((Byte)'n' << 8) | (Byte)'s',
        HB_SCRIPT_CHEROKEE = ((Byte)'C' << 24) | ((Byte)'h' << 16) | ((Byte)'e' << 8) | (Byte)'r',
        HB_SCRIPT_ETHIOPIC = ((Byte)'E' << 24) | ((Byte)'t' << 16) | ((Byte)'h' << 8) | (Byte)'i',
        HB_SCRIPT_KHMER = ((Byte)'K' << 24) | ((Byte)'h' << 16) | ((Byte)'m' << 8) | (Byte)'r',
        HB_SCRIPT_MONGOLIAN = ((Byte)'M' << 24) | ((Byte)'o' << 16) | ((Byte)'n' << 8) | (Byte)'g',
        HB_SCRIPT_MYANMAR = ((Byte)'M' << 24) | ((Byte)'y' << 16) | ((Byte)'m' << 8) | (Byte)'r',
        HB_SCRIPT_OGHAM = ((Byte)'O' << 24) | ((Byte)'g' << 16) | ((Byte)'a' << 8) | (Byte)'m',
        HB_SCRIPT_RUNIC = ((Byte)'R' << 24) | ((Byte)'u' << 16) | ((Byte)'n' << 8) | (Byte)'r',
        HB_SCRIPT_SINHALA = ((Byte)'S' << 24) | ((Byte)'i' << 16) | ((Byte)'n' << 8) | (Byte)'h',
        HB_SCRIPT_SYRIAC = ((Byte)'S' << 24) | ((Byte)'y' << 16) | ((Byte)'r' << 8) | (Byte)'c',
        HB_SCRIPT_THAANA = ((Byte)'T' << 24) | ((Byte)'h' << 16) | ((Byte)'a' << 8) | (Byte)'a',
        HB_SCRIPT_YI = ((Byte)'Y' << 24) | ((Byte)'i' << 16) | ((Byte)'i' << 8) | (Byte)'i',

        HB_SCRIPT_DESERET = ((Byte)'D' << 24) | ((Byte)'s' << 16) | ((Byte)'r' << 8) | (Byte)'t',
        HB_SCRIPT_GOTHIC = ((Byte)'G' << 24) | ((Byte)'o' << 16) | ((Byte)'t' << 8) | (Byte)'h',
        HB_SCRIPT_OLD_ITALIC = ((Byte)'I' << 24) | ((Byte)'t' << 16) | ((Byte)'a' << 8) | (Byte)'l',

        HB_SCRIPT_BUHID = ((Byte)'B' << 24) | ((Byte)'u' << 16) | ((Byte)'h' << 8) | (Byte)'d',
        HB_SCRIPT_HANUNOO = ((Byte)'H' << 24) | ((Byte)'a' << 16) | ((Byte)'n' << 8) | (Byte)'o',
        HB_SCRIPT_TAGALOG = ((Byte)'T' << 24) | ((Byte)'g' << 16) | ((Byte)'l' << 8) | (Byte)'g',
        HB_SCRIPT_TAGBANWA = ((Byte)'T' << 24) | ((Byte)'a' << 16) | ((Byte)'g' << 8) | (Byte)'b',

        HB_SCRIPT_CYPRIOT = ((Byte)'C' << 24) | ((Byte)'p' << 16) | ((Byte)'r' << 8) | (Byte)'t',
        HB_SCRIPT_LIMBU = ((Byte)'L' << 24) | ((Byte)'i' << 16) | ((Byte)'m' << 8) | (Byte)'b',
        HB_SCRIPT_LINEAR_B = ((Byte)'L' << 24) | ((Byte)'i' << 16) | ((Byte)'n' << 8) | (Byte)'b',
        HB_SCRIPT_OSMANYA = ((Byte)'O' << 24) | ((Byte)'s' << 16) | ((Byte)'m' << 8) | (Byte)'a',
        HB_SCRIPT_SHAVIAN = ((Byte)'S' << 24) | ((Byte)'h' << 16) | ((Byte)'a' << 8) | (Byte)'w',
        HB_SCRIPT_TAI_LE = ((Byte)'T' << 24) | ((Byte)'a' << 16) | ((Byte)'l' << 8) | (Byte)'e',
        HB_SCRIPT_UGARITIC = ((Byte)'U' << 24) | ((Byte)'g' << 16) | ((Byte)'a' << 8) | (Byte)'r',

        HB_SCRIPT_BUGINESE = ((Byte)'B' << 24) | ((Byte)'u' << 16) | ((Byte)'g' << 8) | (Byte)'i',
        HB_SCRIPT_COPTIC = ((Byte)'C' << 24) | ((Byte)'o' << 16) | ((Byte)'p' << 8) | (Byte)'t',
        HB_SCRIPT_GLAGOLITIC = ((Byte)'G' << 24) | ((Byte)'l' << 16) | ((Byte)'a' << 8) | (Byte)'g',
        HB_SCRIPT_KHAROSHTHI = ((Byte)'K' << 24) | ((Byte)'h' << 16) | ((Byte)'a' << 8) | (Byte)'r',
        HB_SCRIPT_NEW_TAI_LUE = ((Byte)'T' << 24) | ((Byte)'a' << 16) | ((Byte)'l' << 8) | (Byte)'u',
        HB_SCRIPT_OLD_PERSIAN = ((Byte)'X' << 24) | ((Byte)'p' << 16) | ((Byte)'e' << 8) | (Byte)'o',
        HB_SCRIPT_SYLOTI_NAGRI = ((Byte)'S' << 24) | ((Byte)'y' << 16) | ((Byte)'l' << 8) | (Byte)'o',
        HB_SCRIPT_TIFINAGH = ((Byte)'T' << 24) | ((Byte)'f' << 16) | ((Byte)'n' << 8) | (Byte)'g',

        HB_SCRIPT_BALINESE = ((Byte)'B' << 24) | ((Byte)'a' << 16) | ((Byte)'l' << 8) | (Byte)'i',
        HB_SCRIPT_CUNEIFORM = ((Byte)'X' << 24) | ((Byte)'s' << 16) | ((Byte)'u' << 8) | (Byte)'x',
        HB_SCRIPT_NKO = ((Byte)'N' << 24) | ((Byte)'k' << 16) | ((Byte)'o' << 8) | (Byte)'o',
        HB_SCRIPT_PHAGS_PA = ((Byte)'P' << 24) | ((Byte)'h' << 16) | ((Byte)'a' << 8) | (Byte)'g',
        HB_SCRIPT_PHOENICIAN = ((Byte)'P' << 24) | ((Byte)'h' << 16) | ((Byte)'n' << 8) | (Byte)'x',

        HB_SCRIPT_CARIAN = ((Byte)'C' << 24) | ((Byte)'a' << 16) | ((Byte)'r' << 8) | (Byte)'i',
        HB_SCRIPT_CHAM = ((Byte)'C' << 24) | ((Byte)'h' << 16) | ((Byte)'a' << 8) | (Byte)'m',
        HB_SCRIPT_KAYAH_LI = ((Byte)'K' << 24) | ((Byte)'a' << 16) | ((Byte)'l' << 8) | (Byte)'i',
        HB_SCRIPT_LEPCHA = ((Byte)'L' << 24) | ((Byte)'e' << 16) | ((Byte)'p' << 8) | (Byte)'c',
        HB_SCRIPT_LYCIAN = ((Byte)'L' << 24) | ((Byte)'y' << 16) | ((Byte)'c' << 8) | (Byte)'i',
        HB_SCRIPT_LYDIAN = ((Byte)'L' << 24) | ((Byte)'y' << 16) | ((Byte)'d' << 8) | (Byte)'i',
        HB_SCRIPT_OL_CHIKI = ((Byte)'O' << 24) | ((Byte)'l' << 16) | ((Byte)'c' << 8) | (Byte)'k',
        HB_SCRIPT_REJANG = ((Byte)'R' << 24) | ((Byte)'j' << 16) | ((Byte)'n' << 8) | (Byte)'g',
        HB_SCRIPT_SAURASHTRA = ((Byte)'S' << 24) | ((Byte)'a' << 16) | ((Byte)'u' << 8) | (Byte)'r',
        HB_SCRIPT_SUNDANESE = ((Byte)'S' << 24) | ((Byte)'u' << 16) | ((Byte)'n' << 8) | (Byte)'d',
        HB_SCRIPT_VAI = ((Byte)'V' << 24) | ((Byte)'a' << 16) | ((Byte)'i' << 8) | (Byte)'i',

        HB_SCRIPT_AVESTAN = ((Byte)'A' << 24) | ((Byte)'v' << 16) | ((Byte)'s' << 8) | (Byte)'t',
        HB_SCRIPT_BAMUM = ((Byte)'B' << 24) | ((Byte)'a' << 16) | ((Byte)'m' << 8) | (Byte)'u',
        HB_SCRIPT_EGYPTIAN_HIEROGLYPHS = ((Byte)'E' << 24) | ((Byte)'g' << 16) | ((Byte)'y' << 8) | (Byte)'p',
        HB_SCRIPT_IMPERIAL_ARAMAIC = ((Byte)'A' << 24) | ((Byte)'r' << 16) | ((Byte)'m' << 8) | (Byte)'i',
        HB_SCRIPT_INSCRIPTIONAL_PAHLAVI = ((Byte)'P' << 24) | ((Byte)'h' << 16) | ((Byte)'l' << 8) | (Byte)'i',
        HB_SCRIPT_INSCRIPTIONAL_PARTHIAN = ((Byte)'P' << 24) | ((Byte)'r' << 16) | ((Byte)'t' << 8) | (Byte)'i',
        HB_SCRIPT_JAVANESE = ((Byte)'J' << 24) | ((Byte)'a' << 16) | ((Byte)'v' << 8) | (Byte)'a',
        HB_SCRIPT_KAITHI = ((Byte)'K' << 24) | ((Byte)'t' << 16) | ((Byte)'h' << 8) | (Byte)'i',
        HB_SCRIPT_LISU = ((Byte)'L' << 24) | ((Byte)'i' << 16) | ((Byte)'s' << 8) | (Byte)'u',
        HB_SCRIPT_MEETEI_MAYEK = ((Byte)'M' << 24) | ((Byte)'t' << 16) | ((Byte)'e' << 8) | (Byte)'i',
        HB_SCRIPT_OLD_SOUTH_ARABIAN = ((Byte)'S' << 24) | ((Byte)'a' << 16) | ((Byte)'r' << 8) | (Byte)'b',
        HB_SCRIPT_OLD_TURKIC = ((Byte)'O' << 24) | ((Byte)'r' << 16) | ((Byte)'k' << 8) | (Byte)'h',
        HB_SCRIPT_SAMARITAN = ((Byte)'S' << 24) | ((Byte)'a' << 16) | ((Byte)'m' << 8) | (Byte)'r',
        HB_SCRIPT_TAI_THAM = ((Byte)'L' << 24) | ((Byte)'a' << 16) | ((Byte)'n' << 8) | (Byte)'a',
        HB_SCRIPT_TAI_VIET = ((Byte)'T' << 24) | ((Byte)'a' << 16) | ((Byte)'v' << 8) | (Byte)'t',

        HB_SCRIPT_BATAK = ((Byte)'B' << 24) | ((Byte)'a' << 16) | ((Byte)'t' << 8) | (Byte)'k',
        HB_SCRIPT_BRAHMI = ((Byte)'B' << 24) | ((Byte)'r' << 16) | ((Byte)'a' << 8) | (Byte)'h',
        HB_SCRIPT_MANDAIC = ((Byte)'M' << 24) | ((Byte)'a' << 16) | ((Byte)'n' << 8) | (Byte)'d',

        HB_SCRIPT_CHAKMA = ((Byte)'C' << 24) | ((Byte)'a' << 16) | ((Byte)'k' << 8) | (Byte)'m',
        HB_SCRIPT_MEROITIC_CURSIVE = ((Byte)'M' << 24) | ((Byte)'e' << 16) | ((Byte)'r' << 8) | (Byte)'c',
        HB_SCRIPT_MEROITIC_HIEROGLYPHS = ((Byte)'M' << 24) | ((Byte)'e' << 16) | ((Byte)'r' << 8) | (Byte)'o',
        HB_SCRIPT_MIAO = ((Byte)'P' << 24) | ((Byte)'l' << 16) | ((Byte)'r' << 8) | (Byte)'d',
        HB_SCRIPT_SHARADA = ((Byte)'S' << 24) | ((Byte)'h' << 16) | ((Byte)'r' << 8) | (Byte)'d',
        HB_SCRIPT_SORA_SOMPENG = ((Byte)'S' << 24) | ((Byte)'o' << 16) | ((Byte)'r' << 8) | (Byte)'a',
        HB_SCRIPT_TAKRI = ((Byte)'T' << 24) | ((Byte)'a' << 16) | ((Byte)'k' << 8) | (Byte)'r',

        HB_SCRIPT_BASSA_VAH = ((Byte)'B' << 24) | ((Byte)'a' << 16) | ((Byte)'s' << 8) | (Byte)'s',
        HB_SCRIPT_CAUCASIAN_ALBANIAN = ((Byte)'A' << 24) | ((Byte)'g' << 16) | ((Byte)'h' << 8) | (Byte)'b',
        HB_SCRIPT_DUPLOYAN = ((Byte)'D' << 24) | ((Byte)'u' << 16) | ((Byte)'p' << 8) | (Byte)'l',
        HB_SCRIPT_ELBASAN = ((Byte)'E' << 24) | ((Byte)'l' << 16) | ((Byte)'b' << 8) | (Byte)'a',
        HB_SCRIPT_GRANTHA = ((Byte)'G' << 24) | ((Byte)'r' << 16) | ((Byte)'a' << 8) | (Byte)'n',
        HB_SCRIPT_KHOJKI = ((Byte)'K' << 24) | ((Byte)'h' << 16) | ((Byte)'o' << 8) | (Byte)'j',
        HB_SCRIPT_KHUDAWADI = ((Byte)'S' << 24) | ((Byte)'i' << 16) | ((Byte)'n' << 8) | (Byte)'d',
        HB_SCRIPT_LINEAR_A = ((Byte)'L' << 24) | ((Byte)'i' << 16) | ((Byte)'n' << 8) | (Byte)'a',
        HB_SCRIPT_MAHAJANI = ((Byte)'M' << 24) | ((Byte)'a' << 16) | ((Byte)'h' << 8) | (Byte)'j',
        HB_SCRIPT_MANICHAEAN = ((Byte)'M' << 24) | ((Byte)'a' << 16) | ((Byte)'n' << 8) | (Byte)'i',
        HB_SCRIPT_MENDE_KIKAKUI = ((Byte)'M' << 24) | ((Byte)'e' << 16) | ((Byte)'n' << 8) | (Byte)'d',
        HB_SCRIPT_MODI = ((Byte)'M' << 24) | ((Byte)'o' << 16) | ((Byte)'d' << 8) | (Byte)'i',
        HB_SCRIPT_MRO = ((Byte)'M' << 24) | ((Byte)'r' << 16) | ((Byte)'o' << 8) | (Byte)'o',
        HB_SCRIPT_NABATAEAN = ((Byte)'N' << 24) | ((Byte)'b' << 16) | ((Byte)'a' << 8) | (Byte)'t',
        HB_SCRIPT_OLD_NORTH_ARABIAN = ((Byte)'N' << 24) | ((Byte)'a' << 16) | ((Byte)'r' << 8) | (Byte)'b',
        HB_SCRIPT_OLD_PERMIC = ((Byte)'P' << 24) | ((Byte)'e' << 16) | ((Byte)'r' << 8) | (Byte)'m',
        HB_SCRIPT_PAHAWH_HMONG = ((Byte)'H' << 24) | ((Byte)'m' << 16) | ((Byte)'n' << 8) | (Byte)'g',
        HB_SCRIPT_PALMYRENE = ((Byte)'P' << 24) | ((Byte)'a' << 16) | ((Byte)'l' << 8) | (Byte)'m',
        HB_SCRIPT_PAU_CIN_HAU = ((Byte)'P' << 24) | ((Byte)'a' << 16) | ((Byte)'u' << 8) | (Byte)'c',
        HB_SCRIPT_PSALTER_PAHLAVI = ((Byte)'P' << 24) | ((Byte)'h' << 16) | ((Byte)'l' << 8) | (Byte)'p',
        HB_SCRIPT_SIDDHAM = ((Byte)'S' << 24) | ((Byte)'i' << 16) | ((Byte)'d' << 8) | (Byte)'d',
        HB_SCRIPT_TIRHUTA = ((Byte)'T' << 24) | ((Byte)'i' << 16) | ((Byte)'r' << 8) | (Byte)'h',
        HB_SCRIPT_WARANG_CITI = ((Byte)'W' << 24) | ((Byte)'a' << 16) | ((Byte)'r' << 8) | (Byte)'a',

        HB_SCRIPT_AHOM = ((Byte)'A' << 24) | ((Byte)'h' << 16) | ((Byte)'o' << 8) | (Byte)'m',
        HB_SCRIPT_ANATOLIAN_HIEROGLYPHS = ((Byte)'H' << 24) | ((Byte)'l' << 16) | ((Byte)'u' << 8) | (Byte)'w',
        HB_SCRIPT_HATRAN = ((Byte)'H' << 24) | ((Byte)'a' << 16) | ((Byte)'t' << 8) | (Byte)'r',
        HB_SCRIPT_MULTANI = ((Byte)'M' << 24) | ((Byte)'u' << 16) | ((Byte)'l' << 8) | (Byte)'t',
        HB_SCRIPT_OLD_HUNGARIAN = ((Byte)'H' << 24) | ((Byte)'u' << 16) | ((Byte)'n' << 8) | (Byte)'g',
        HB_SCRIPT_SIGNWRITING = ((Byte)'S' << 24) | ((Byte)'g' << 16) | ((Byte)'n' << 8) | (Byte)'w',

        HB_SCRIPT_ADLAM = ((Byte)'A' << 24) | ((Byte)'d' << 16) | ((Byte)'l' << 8) | (Byte)'m',
        HB_SCRIPT_BHAIKSUKI = ((Byte)'B' << 24) | ((Byte)'h' << 16) | ((Byte)'k' << 8) | (Byte)'s',
        HB_SCRIPT_MARCHEN = ((Byte)'M' << 24) | ((Byte)'a' << 16) | ((Byte)'r' << 8) | (Byte)'c',
        HB_SCRIPT_OSAGE = ((Byte)'O' << 24) | ((Byte)'s' << 16) | ((Byte)'g' << 8) | (Byte)'e',
        HB_SCRIPT_TANGUT = ((Byte)'T' << 24) | ((Byte)'a' << 16) | ((Byte)'n' << 8) | (Byte)'g',
        HB_SCRIPT_NEWA = ((Byte)'N' << 24) | ((Byte)'e' << 16) | ((Byte)'w' << 8) | (Byte)'a',

        HB_SCRIPT_MASARAM_GONDI = ((Byte)'G' << 24) | ((Byte)'o' << 16) | ((Byte)'n' << 8) | (Byte)'m',
        HB_SCRIPT_NUSHU = ((Byte)'N' << 24) | ((Byte)'s' << 16) | ((Byte)'h' << 8) | (Byte)'u',
        HB_SCRIPT_SOYOMBO = ((Byte)'S' << 24) | ((Byte)'o' << 16) | ((Byte)'y' << 8) | (Byte)'o',
        HB_SCRIPT_ZANABAZAR_SQUARE = ((Byte)'Z' << 24) | ((Byte)'a' << 16) | ((Byte)'n' << 8) | (Byte)'b',

        HB_SCRIPT_INVALID = 0,
    }
#pragma warning restore 1591
}
